version: "3.9" # optional since v1.27.0

services:
  dotnet:
    build: dotnet
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5171;http://0.0.0.0:80
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5080:80"
      - "5443:443"
      - "5081:7171"
      - "5082:5171"
